"use strict";
console.log("Hey Abu Hurairah, I have started learning TYPESCRIPT.");
var Name = "Muhammad Umair";
console.log("My Name is ", Name);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var sum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10;
console.log("Sum of all numbers", sum);
var subtract = num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10;
console.log("Subration", subtract);
var multiply = num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10;
console.log("Multiplying", multiply);
var division = num10 / num5;
console.log("Division", division);
